name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean existing Colima files
        run: |
          # Ensure Colima is stopped
          colima stop || true
          colima delete || true
          
          # Clean up any existing files
          rm -rf ~/.colima
          rm -rf /Users/runner/.colima
          
          # Create fresh directory
          mkdir -p ~/.colima

      - name: Install Dependencies
        run: |
          brew uninstall --force qemu colima docker docker-compose || true
          brew update
          brew install qemu
          brew install colima docker docker-compose
          
          # Check architecture and QEMU installation
          arch
          which qemu-system-aarch64
          ls -l /opt/homebrew/share/qemu/

      - name: Start Colima
        run: |
          # Start with specific architecture settings
          colima start --vm-type=qemu \
            --arch aarch64 \
            --cpu 2 \
            --memory 4 \
            --disk 40 \
            --vm-options="-M virt,highmem=off" \
            --verbose
          
          # Wait for Colima to be ready
          for i in {1..30}; do
            if colima status; then
              echo "Colima is running!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Colima failed to start"
              cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
              exit 1
            fi
            echo "Waiting for Colima to start... (Attempt $i/30)"
            sleep 10
          done

      - name: Verify Docker Installation
        timeout-minutes: 5
        run: |
          for i in {1..30}; do
            if docker version && docker-compose version && docker info; then
              echo "Docker is running!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Docker failed to initialize"
              exit 1
            fi
            echo "Waiting for Docker... (Attempt $i/30)"
            sleep 10
          done

      - name: Build and Start Services
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d

      - name: Check Running Containers
        run: |
          docker ps -a

      - name: Run Airflow Health Check
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8080/health; then
              echo "Airflow is healthy!"
              exit 0
            fi
            if [ $i -eq 30 ]; then
              echo "Airflow failed to become healthy"
              exit 1
            fi
            echo "Waiting for Airflow... (Attempt $i/30)"
            sleep 10
          done

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          colima status || true
          docker-compose -f airflow/docker-compose.yaml logs || true
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
          ls -la ~/.colima || true
          ls -la /Users/runner/.colima/_lima/colima/ || true

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down || true
          colima stop || true
          colima delete || true
          rm -rf ~/.colima || true
          rm -rf /Users/runner/.colima || true