name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Desktop and Docker Compose
        run: |
          brew install --cask docker
          brew install docker-compose
          # Start Docker Desktop
          open /Applications/Docker.app
          # Wait for Docker Desktop to initialize. You may adjust the sleep duration if needed.
          sleep 30

      - name: Verify Docker Installation
        run: |
          docker --version
          docker-compose --version

      - name: Wait for Docker Daemon to Start
        run: |
          while ! docker info >/dev/null 2>&1; do
            echo "Waiting for Docker daemon to start..."
            sleep 5
          done
          echo "Docker is up and running!"

      - name: Build and Start Services
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d

      - name: Check Running Containers
        run: |
          docker ps -a

      - name: Run Airflow Webserver Health Check
        run: |
          sleep 15
          curl -f http://localhost:8080/health || exit 1

      - name: Debug Logs (if failure)
        if: failure()
        run: |
          docker-compose -f airflow/docker-compose.yaml logs

      - name: Stop Containers
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down
