name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Clean existing Colima setup
        run: |
          colima stop || true
          colima delete || true
          rm -rf ~/.colima
          mkdir -p ~/.colima

      - name: Install Dependencies
        run: |
          brew install colima docker docker-compose qemu

      - name: Start Colima
        run: |
          colima start --cpu 4 --memory 8 --disk 60 --arch amd64 --vm-type qemu
          
          # Wait for Colima to be ready
          for i in {1..30}; do
            if colima status; then
              echo "Colima is running!"
              break
            fi
            echo "Waiting for Colima... (Attempt $i/30)"
            sleep 10
          done

      - name: Setup directories
        run: |
          mkdir -p airflow/logs airflow/dags airflow/data airflow/plugins
          chmod -R 777 airflow/

      - name: Build images
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --load \
            -t custom-airflow:latest \
            -f airflow/Dockerfile .

      - name: Start services
        run: |
          docker-compose -f airflow/docker-compose.yaml up -d
          
          # Monitor startup
          for i in {1..60}; do
            if docker-compose -f airflow/docker-compose.yaml ps | grep -q "airflow-init.*Exit 0"; then
              echo "Initialization completed successfully!"
              break
            fi
            echo "Waiting for initialization... (Attempt $i/60)"
            docker-compose -f airflow/docker-compose.yaml logs airflow-init
            sleep 10
          done

      - name: Check services
        run: |
          docker ps -a
          docker-compose -f airflow/docker-compose.yaml logs

      - name: Verify Airflow
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8080/health; then
              echo "Airflow is healthy!"
              exit 0
            fi
            echo "Waiting for Airflow... (Attempt $i/30)"
            sleep 10
          done

      - name: Debug (on failure)
        if: failure()
        run: |
          echo "--- Docker Info ---"
          docker info
          echo "--- Container Status ---"
          docker ps -a
          echo "--- Init Container Logs ---"
          docker-compose -f airflow/docker-compose.yaml logs airflow-init
          echo "--- All Logs ---"
          docker-compose -f airflow/docker-compose.yaml logs

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down -v
          colima stop
          colima delete