name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean existing Colima files
        run: |
          colima stop || true
          colima delete || true
          rm -rf ~/.colima
          rm -rf /Users/runner/.colima
          mkdir -p ~/.colima

      - name: Install Dependencies
        run: |
          brew uninstall --force qemu colima docker docker-compose || true
          brew update
          brew install qemu
          brew install colima docker docker-compose

      - name: Configure Lima
        run: |
          mkdir -p ~/.lima/default
          cat <<-'EOF' > ~/.lima/default/lima.yaml
          images:
          - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
            arch: "x86_64"
          vmType: "qemu"
          EOF

      - name: Setup Airflow directories
        run: |
          mkdir -p airflow/logs
          mkdir -p airflow/dags
          mkdir -p airflow/data
          mkdir -p airflow/plugins
          chmod -R 777 airflow/logs
          chmod -R 777 airflow/dags
          chmod -R 777 airflow/data
          chmod -R 777 airflow/plugins
          ls -la airflow/

      - name: Start Colima
        run: |
          colima start --arch x86_64 --cpu 2 --memory 4 --disk 40 --vm-type qemu --verbose
          for i in {1..30}; do
            if colima status; then
              echo "Colima is running!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Colima failed to start"
              cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
              exit 1
            fi
            echo "Waiting for Colima to start... (Attempt $i/30)"
            sleep 10
          done

      - name: Use Colima Docker Context
        run: |
          docker context use colima

      - name: Verify Docker Installation
        timeout-minutes: 5
        run: |
          for i in {1..30}; do
            if docker version && docker-compose version && docker info; then
              echo "Docker is running!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Docker failed to initialize"
              exit 1
            fi
            echo "Waiting for Docker... (Attempt $i/30)"
            sleep 10
          done

      - name: Build and Start Services
        run: |
          ls -la airflow/
          docker-compose -f airflow/docker-compose.yaml up --build -d
          docker-compose -f airflow/docker-compose.yaml ps
          docker volume ls

      - name: Check Running Containers
        run: docker ps -a

      - name: Run Airflow Health Check
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8080/health; then
              echo "Airflow is healthy!"
              exit 0
            fi
            if [ $i -eq 30 ]; then
              echo "Airflow failed to become healthy"
              exit 1
            fi
            echo "Waiting for Airflow... (Attempt $i/30)"
            sleep 10
          done

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          colima status || true
          docker-compose -f airflow/docker-compose.yaml logs || true
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
          ls -la ~/.colima || true
          ls -la /Users/runner/.colima/_lima/colima/ || true
          ls -la airflow/ || true

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down || true
          colima stop || true
          colima delete || true
          rm -rf ~/.colima || true
          rm -rf /Users/runner/.colima || true
