name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install qemu
          brew install colima docker docker-compose

      - name: Start Colima with explicit configuration
        run: |
          # Stop any existing Colima instance
          colima stop || true
          colima delete || true
          
          # Start with explicit resource allocation and debug logging
          colima start --vm-type=qemu --cpu 4 --memory 8 --disk 60 --verbose
          
          # Wait for Colima to be ready
          for i in {1..30}; do
            if colima status; then
              echo "Colima is running!"
              break
            fi
            echo "Waiting for Colima to start... (Attempt $i/30)"
            sleep 10
          done

      - name: Verify Docker Installation
        run: |
          docker version
          docker-compose version
          docker info

      - name: Build and Start Services
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d

      - name: Check Running Containers
        run: |
          docker ps -a

      - name: Run Airflow Health Check
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8080/health; then
              echo "Airflow is healthy!"
              exit 0
            fi
            echo "Waiting for Airflow... (Attempt $i/30)"
            sleep 10
          done
          echo "Airflow failed to become healthy"
          exit 1

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          colima status
          docker-compose -f airflow/docker-compose.yaml logs
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down
          colima stop
          colima delete
