name: MacOS Docker Test

on:
  push:
    branches:
      - master  # Runs on master branch
  pull_request:
    branches:
      - master  # Runs on master branch

jobs:
  test-macos:
    runs-on: macos-latest  # Use macOS runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Get the latest code from repo

      - name: Install Colima and Docker
        run: |
          brew install colima docker docker-compose
          colima start  # Start lightweight Docker runtime

      - name: Verify Docker and Docker Compose Installation
        run: |
          docker --version
          docker-compose --version

      - name: Check Docker Daemon Status
        run: |
          while ! docker info >/dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 5
          done
          echo "Docker is up and running!"

      - name: Build and Start Services
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d

      - name: Check Running Containers
        run: |
          docker ps -a  # Verify if containers are running

      - name: Run Airflow Webserver Health Check
        run: |
          sleep 15  # Give Airflow some time to start
          curl -f http://localhost:8080/health || exit 1  # Ensure Airflow webserver is running

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          docker-compose -f airflow/docker-compose.yaml logs

      - name: Stop Containers
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down
