name: MacOS Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean existing Colima files
        run: |
          colima stop || true
          colima delete || true
          rm -rf ~/.colima /Users/runner/.colima
          mkdir -p ~/.colima

      - name: Install Dependencies
        run: |
          brew uninstall --force colima docker docker-compose || true
          brew update
          brew install colima docker docker-compose

      - name: Setup Airflow directories
        run: |
          mkdir -p airflow/{logs,dags,data,plugins}
          chmod -R 777 airflow/{logs,dags,data,plugins}
          ls -la airflow/

      - name: Start Colima with vz and Rosetta
        run: |
          colima start \
            --cpu 2 \
            --memory 4 \
            --disk 40 \
            --vm-type vz \
            --vz-rosetta \
            --verbose
          
          for i in {1..30}; do
            if colima status; then
              echo "Colima is running!"
              break
            fi
            [ $i -eq 30 ] && echo "Colima failed to start" && exit 1
            echo "Waiting for Colima... (Attempt $i/30)"
            sleep 10
          done

      - name: Verify Docker Installation
        timeout-minutes: 5
        run: |
          for i in {1..30}; do
            if docker version && docker-compose version && docker info; then
              echo "Docker is running!"
              break
            fi
            [ $i -eq 30 ] && echo "Docker failed" && exit 1
            echo "Waiting for Docker... (Attempt $i/30)"
            sleep 10
          done

      - name: Build and Start Services
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d
          docker-compose -f airflow/docker-compose.yaml ps
          docker volume ls

      - name: Check Running Containers
        run: |
          docker ps -a

      - name: Run Airflow Health Check
        run: |
          for i in {1..30}; do
            curl -sf http://localhost:8080/health && exit 0
            [ $i -eq 30 ] && echo "Airflow unhealthy" && exit 1
            echo "Waiting for Airflow... (Attempt $i/30)"
            sleep 10
          done

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          colima status || true
          docker-compose -f airflow/docker-compose.yaml logs || true
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f airflow/docker-compose.yaml down || true
          colima stop || true
          colima delete || true
          rm -rf ~/.colima /Users/runner/.colima