name: MacOS Docker Test

on:
  push:
    branches:
      - master  # Changed from main to master
  pull_request:
    branches:
      - master  # Changed from main to master

jobs:
  test-macos:
    runs-on: macos-latest  # Use macOS as the test environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Get the latest code from the repo

      - name: Install Docker and Docker Compose
        run: |
          brew install --cask docker
          brew install docker-compose
          open /Applications/Docker.app  # Start Docker Desktop
          sleep 30  # Wait for Docker to initialize

      - name: Verify Docker and Docker Compose Installation
        run: |
          docker --version
          docker-compose --version

      - name: Check Docker Daemon Status
        run: |
          while ! docker info >/dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 5
          done
          echo "Docker is up and running!"

      - name: Build and Start Services with Specified Docker Compose File
        run: |
          docker-compose -f airflow/docker-compose.yaml up --build -d

      - name: Check Running Containers
        run: |
          docker ps -a  # Verify if containers are running

      - name: Run Airflow Webserver Health Check
        run: |
          sleep 15  # Give Airflow some time to start
          curl -f http://localhost:8080/health || exit 1  # Ensure Airflow webserver is running

      - name: Debug Logs (If Failure)
        if: failure()
        run: |
          docker-compose -f airflow/docker-compose.yaml logs

      - name: Stop Containers
        if: always()  # Always stop containers, even if tests fail
        run: |
          docker-compose -f airflow/docker-compose.yaml down
